### ISSUE TITLE
Show/Hide password

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#332]
### Stories - what are the use cases for different personas?

1. User wants to see the password they are typing but by default it is hidden.

### Proposal - how do we solve these problems?

Have a little eye icon on the right of the input that shows on hover so you can show/hide the currently typed password.

### TODO - Actionable steps to solve this

- [ ] Password component that has an eye button that shows/hides password.
- [ ] Main AYON login page.
- [ ] Create new user popup.
- [ ] Secrets page.

### Attachments

![image](https://github.com/ynput/ayon-frontend/assets/49156310/9fa9302c-7346-42dc-863d-32dc45b2e08a)

![image](https://github.com/ynput/ayon-frontend/assets/49156310/550c8cf8-1071-4089-864c-f593ee1b6775)

icons to use
![image](https://github.com/ynput/ayon-frontend/assets/49156310/54e01e19-6f86-473a-8e5c-c94f856ef473)

**Comment by martastain** [comment]
The same would be useful for secrets actually.

**Comment by Innders** [comment]
> The same would be useful for secrets actually.

Thanks, I've updated the description. Also creating a new user.

**Comment by LudoHolbik** [comment]
I decided to solve this issue in ARC rather than in this ayon-frontend repository. At least one of requested places uses type="text", and is not a password. I have added "hiding" toggle for both text and password input. Further description in ARC PR.

Link to PR:
https://github.com/ynput/ayon-react-components/pull/72
