### ISSUE TITLE
Reference another entity or user on a comment

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#342]
### Stories

- As a supervisor I want to comment on a version and mention a representation to be used down the line.
-  As an artist I want to ask an artist from a precursor task about something they did.
- As a supervisor I want to let others know that a comment I'm making is relevant to them too.

### Problems to solve

1. Ability to reference any entity inside of a comment
2. What triggers are used?
3. How are the query recommendations calculated (on client or server)?
4. What is the scope of the recommendations, do you only see tasks in the same folder?
5. How are the references stored in the body?

### Tag characters

- [x] `@` is universally used for **users**.
- [x] `@@` for **versions** on the task.
- [x] `@@@` for sibling **tasks**.
- [ ] `#` for any other entity that isn't specifically scoped to the task.

Could pasting in a URI create a reference, that might be easier than searching for `shot020/compositing`?

### Reference storage

- Stored in the body as a special markdown link `[reference label](type:id)` `[Animation](task:ccc0e72410cf11ee9ad50242ac190004)
- Could the original query also be stored and is it even useful? `[Lias Wallin](user:lias:'director')`

### TODO

- [ ] Backend 
- [ ] Search algorithm
- [ ] Search popup design
- [ ] Frontend
