### ISSUE TITLE
Easily set up tasks and assignments for many shots

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#343]
### Stories - what are the use cases for different personas?

As a production manager you easily want to set up many shots, their tasks and often the assignees.

### Problems - what problems does this story create?

A production often comes with some sort of template (in your head) on how you'll be doing the next few assets or shots, with which tasks and often even who would be assigned.

### Proposal - how do we solve these problems?

It should be very easy to easily select the relevant assets (and/or create them) to add and manipulate their tasks and assignees.

##### Support copy - pasting

In Ftrack what we would often do is, create one asset with the relevant tasks and assignees (and sometimes even other bits like due dates) and use that one asset as the template of the 10s of others I need to add now, by just copy pasting the assets, or sometimes just the tasks.

##### Make it easy to filter to just the relevant assets or tasks. (e.g. filter by folder type or task type)

To quickly assign e.g. all "animation" tasks for a few assets to a particular assignee I currently need to go one by one clicking each of the animation tasks, instead of just filtering to all animation tasks and adding the assignees, then filtering to all lighting and set the assignees for lighting.

### TODO - Actionable steps to solve this

- [ ] Allow copy/pasting tasks
- [ ] Allow copy/pasting folders
- [ ] Add filter by task type so one can easily select e.g. all animation tasks under a specific folder hierarchy. (Preferably then it's also easy to select all these tasks instead of having to one by one select them under each folder)

**Comment by Innders** [comment]
I like the idea and copy/pasting will need to be added. We are also need to think about templates and this feeds into a that bigger discussion.

FYI you can already filter by task type using the search bar. But I just realised you can only filter by one task type at one time. So maybe a dropdown filter option is needed 🤔 


https://github.com/ynput/ayon-frontend/assets/49156310/4a4f717b-f10e-4768-b061-dec69011c1bd

**Comment by Innders** [comment]
> I need to refresh before seeing the new value after saving.

Hmm I can't seem to replicate this

**Comment by mkolar** [comment]
This is directly related to the projects templates epic. Adding it to it.

**Comment by mkolar** [comment]
We've now completed the work on project and entity templates (coming imminently to Power feature). That could very well unlock copy pasting as well
