### ISSUE TITLE
Browser: View only products that belong to specific task in the browser AY-4592

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#423]
## Story

You only want to see versions/products linked to a specific task.

### Proposal

A filtering option at the top of versions list that will let you filter by taskType.

## TODO

- [x] Task type dropdown with clear option
- [x] Filter versions/products table based on tasks selected
- [x] Context menu on task table "Filter products by task{s}"
- [ ] #428

### Attachments

![image](https://github.com/ynput/ayon-frontend/assets/49156310/e0fc09ef-e3ae-431b-a450-0f4dfc42d8fa)
