### ISSUE TITLE
Shortcuts: Services and Market Page

### ISSUE THREAD

**Issue by MadsHangaard** [ynput/ayon-frontend#436]
## Story

When working on the Ayon-Kitsu addon, I often want to go to the services page. And being used to using S+S for Studio Settings and E+E for Event Viewer, going to the pages menu in the top right feels slow.

### Problems

It will save me .2 seconds every time I go to the Services page.

### Proposal

Adding a shortcut similar to Studio Settings, I suggest V+V. I will also suggest adding one to Addon Market just because short cuts are nice.

## TODO

- Add shortcut for Services page
- Add shortcut for Addon Market page

**Comment by Innders** [comment]
- [ ] v+v: services page
- [ ] m+m: addon market page
- [ ] Check m+m works on editor page as it clashes with "New Sequence"
- [ ] menu shortcut tooltips
