### ISSUE TITLE
Bundles: Archive bundle shortcut

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#471]
## Story

You want to quickly archive a lot of bundles.

`/settings/bundles`

## TODO

- [ ] `A` (Shift+A) when selected on a bundle/s to archive/unarchive it.
- [ ] When the bundle is archived select the next bundle.
- [ ] Add shortcut to context menu.

### Attachments

![image](https://github.com/ynput/ayon-frontend/assets/49156310/f25a5060-a5a6-4fdb-babf-d1456e85d1ad)
