### ISSUE TITLE
Copy Settings: Show the actual differences being copied.

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#495]
## Story

The Copy Settings UX should display the differences correctly and only 'copy' the actual changes between my current settings and the bundle I'm copying from.

### Problems

The Copy Setting for bundles view in the front-end seems to currently:

> lists everything what has a pinned/overriden value in the source, but it should also take in account the destination and do the comparison.

But I'd expect it to really be a visual "diff" of what will be the resulting changes from that copy.

#### Not all settings are being copied

Here's my production bundle:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/d0116c50-e778-4d6c-ab93-117e8565f6d8)

Here's my dev bundle:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/f4e8a084-d2db-402b-8c87-c66777fb8773)

Copying the production bundle to my dev bundle does **NOT** revert it currently back to the default value whereas, to my understanding, it should since I want to copy the settings of that bundle. One to one.

It's not shown when clicking:
![image](https://github.com/ynput/ayon-frontend/assets/2439881/029bf0a2-5487-4faa-aa7c-ebe27649ec4f)

![image](https://github.com/ynput/ayon-frontend/assets/2439881/85c66e7d-e152-43a3-990f-4d28dd23a4f8)

#### However it does show 'diffs' that are actually at the same value

Yet it does show these differences that are 1:1 matching values. I'd expect these to **not** be listed.

![copy_settings_1to1](https://github.com/ynput/ayon-frontend/assets/2439881/bae34056-c372-403f-bb6f-57931c7b48f6)

### Proposal

- Copy default values from a bundle into my bundle if my current bundle has an override.
    - If this is 'user preference' then maybe the copy UI should have a toggle that states "Lock current overrides in bundle" with a tooltip describing that when enabled it ignores copying to any attribute that currently has an override in my existing bundle?
- Show only the differences - never show identical values/states.
- To ensure that "pinned overrides" visualize nicely in the bundle to copy from for which those and my current values are at the _default_ value but not pinned in my current settings I think we should add the color highlighting similar to what settings show. So, if I copy _just the pinning_ but the value other than is the same that it's clear that my current value is white (default) and turns green (overridden)

## TODO

- [x] Show only differences
- [x] Also copy non-overridden values from a source bundle
- [x] Color code the state of what you're copying (is the result of the copy a default value, or an override?)

### Attachments

Also came up on [Discord](https://discord.com/channels/517362899170230292/890894521817260052/1247140702148886528) which states some reasons why it ended up working the way it currently does.

**Comment by martastain** [comment]
@BigRoy ad color coding: something like this?

![image](https://github.com/ynput/ayon-frontend/assets/5007200/0eee8813-1282-461d-9d76-1e270cf5572d)

**Comment by martastain** [comment]
It is now possible to "copy unpins" as well.

https://github.com/ynput/ayon-frontend/assets/5007200/fe284126-c59b-4ad5-ae02-64c957c5d394

**Comment by BigRoy** [comment]
> @BigRoy ad color coding: something like this?
> 
> ![image](https://private-user-images.githubusercontent.com/5007200/340300704-0eee8813-1282-461d-9d76-1e270cf5572d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTgxOTQsIm5iZiI6MTcxODY5Nzg5NCwicGF0aCI6Ii81MDA3MjAwLzM0MDMwMDcwNC0wZWVlODgxMy0xMjgyLTQ2MWQtOWQ3Ni0xZTI3MGNmNTU3MmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDgwNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdmNTZiYzY3MmUxMTU0MDMzNzBmMDY5N2IxYmVkYTczMTVmZTdhY2M4ZjUyYmI5ODE2ZThkYzhhNDgxMTUyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cjlGoIzS5dlGpX5nLG_SJ1scBU9dNIh7kSTRHFa4ojw)

I like it! Just saw a `dev` tag being pushed so I'll be checking this out.

**Comment by BigRoy** [comment]
Just want to add that I'm still seeing "Copy settings" for things that have the same values, e.g.:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/41efa65c-e53b-4433-8ba7-3f81c50d8e65)

Not sure if there's a reason to show those - but I'd love to be able to quickly identify things that are only changes that will occur on the copy. So I'd personally love these filtered out.

This could be:
- Always filter out same values
- Or add a toggle (default: on) to filter out matching values?
- Or make these particular entries in the visual diff a more dull gray so they stand out less.

**Comment by BigRoy** [comment]
@martastain I feel like this diff is also wrong:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/03e0d114-74f9-4101-95fd-b07b239137cb)

These three entries are all just there because they are all "diffs" about the same resulting child key.
Or maybe this particular one is just a frontend issue?

**Comment by martastain** [comment]
Ah. True. That top-level item is redundant. 

It depends on whether children elements are "grouped" or not (grouping implicit for arrays, but can be specified for certain submodels of settings - it is up to the addon author. In the case of grouped settings, it should display only that top-level entry, while in the case of ungrouped settings (with independent fields) it should show only the children fields and not the top level one.

Thanks!

**Comment by martastain** [comment]
It SHOULD be fixed in https://github.com/ynput/ayon-frontend/pull/544

**Comment by BigRoy** [comment]
Yes, seems fixed in latest `dev` tag as well with server `1.2.3+202406201258`.

There is however [this](https://discord.com/channels/517362899170230292/1253229518840397894/1253312180216926258) to still consider:

> When changing only this field: `ayon+settings://applications/applications/fusion/variants/2/environment`

![a](https://github.com/ynput/ayon-frontend/assets/2439881/ecc8f11c-02e1-4bff-b764-403fbf139a35)

> And then Copy Settings for the addon from previous addon version then the frontend lists this as diff:

![b](https://github.com/ynput/ayon-frontend/assets/2439881/80976b56-7dc9-48c4-858a-a9ce9532b638)
![c](https://github.com/ynput/ayon-frontend/assets/2439881/95fd646d-9a64-44a3-86b7-deefe9a14319)

> Which functionally works, it's just completely unclear what in that nested hierarchy ACTUALLY changed.
> (Although then clicking Copy Settings and checking the current state before save may allow you to investigate that more) 
> So not critical - but something maybe worth noting for future improvements.
> It looks like the diff now shows the "highest level diff" which is fine but it could be nice to have that displayed more granularly (showing only the lowest mismatch instead of the highest group one).
> Nonetheless, this is functional.

![d](https://github.com/ynput/ayon-frontend/assets/2439881/72382279-76d6-44fa-9763-43adbb1964b5)

> e.g. here you can't see the actual differences in values for the deadline URL itself. 
>Even though the actual change is on `ayon+settings://deadline/deadline_urls/0/value` 
> Again, nice-to-have to have that displayed "better" I suppose.

![e](https://github.com/ynput/ayon-frontend/assets/2439881/9f012022-0da0-47f5-be23-c4e810f00615)

**Comment by martastain** [comment]
I've created a separate issue for that
