### ISSUE TITLE
Settings: Add search

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#570]
## Story

There are many addons with many settings and across the web of interconnected little pieces it can sometimes be hard to find _just that_ setting you're looking for.

### Problems

A good search or filter to what you're looking for.

### Proposal

Add a search bar.

Potentially fill this nice little gap above the settings in frontend:

![fill_the_gap](https://github.com/ynput/ayon-frontend/assets/2439881/9d5127a0-f292-4064-a409-d9ae5ed38418)

For searching it may become worth it to suddenly also be able to describe certain settings with tags or keywords on the backend.

Would be great if clicking the settings from e.g. a preview widget of what settings may match  your search (if it doesn't actually filter the settings UI itself) it would be great if it could expand to the attribute and bring the attribute in view + activate it.

### TODO

- [ ] Add search bar
- [ ] Ask Martin to write a crazy backend search query; or don't - just make the search work.
- [ ] Now also fix it for project settings, because of course we forget that first.

### Attachments

OpenPype settings UI had a similar feature (hidden with shortcut CTRL+F)
It would search across all studio settings or project anatomy + project addon settings.

See:
![image](https://github.com/ynput/ayon-frontend/assets/2439881/8d4d7bb9-c2cd-4aa1-84bc-741360edaed4)

![image](https://github.com/ynput/ayon-frontend/assets/2439881/0ffffb69-4d31-4115-8516-08d2fd4f17b7)
![image](https://github.com/ynput/ayon-frontend/assets/2439881/c1744c44-f66f-4cab-bc5c-e9013d05aa8e)

Clicking the entry in the search would bring the settings UI itself towards that field:
![image](https://github.com/ynput/ayon-frontend/assets/2439881/a580a082-90f5-4606-9330-c34e865153a3)

**Comment by martastain** [comment]
I am surprised there isn't an issue for this already. 
- totally makes sense
- we need tags support in the SettingsField 
- otherwise it is just a frontend thing

**Comment by m-u-r-p-h-y** [comment]
what I did not like in OP was the inability to search for values

**Comment by Innders** [comment]
#870

**Comment by Innders** [comment]
Duplicate of completed #870
