### ISSUE TITLE
Projects: Show and manage pinned projects in main projects list

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#577]
## Story

A studio has 100s of projects but might only be working on one project.

### Proposal

Just like how the project menu has pinned projects, do the same for the main project list. They will be synced.

![image](https://github.com/ynput/ayon-frontend/assets/49156310/b77cfd9c-9348-41bf-ba44-2e870d43065f)

## TODO

- [ ] Sort pinned to the top
- [ ] Show little pin icon next to pinned
- [ ] Right click to pin/unpin project
