### ISSUE TITLE
🚀 Support: Customerly inside AYON for clients

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#586]
## Story

- A client wants some support about a feature inside AYON.
- A client/customer wants some more information.
- The CS team want to be able to match a support request to an client automatically.

### Problems

- Only show support bubble for clients that have a support subscription.
- Provide the right context to customerly.
- Is this only for admins and managers?

## TODO

- [ ] Get customerly working inside AYON
- [ ] Limit to the right subscription
- [ ] Send relevant context
