### ISSUE TITLE
Viewer: Quicker View mode

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#595]
## Story

Quickly preview a version on a task or product.

### Proposal

Press spacebar when a folder/task/product is selected to show the latest version in a "Quick View" dialog.

Quick view is a stripped down version of Viewer.

Pressing `shift+spacebar` opens straight to viewer and pressing `shift` whilst the Quick View is open will it in full "Viewer"

When in Quick View you should be able to navigate the folder/task/product selection using the up/down arrow keys.

Quick View is the same component as Viewer but with the reviewables and feed hidden.

## TODO

- [ ] Using up/down arrows selects next item in browser and tasks.
- [ ] New state `quickView` for Viewer that hides reviewables column and details column.
- [ ] New top right button to switch Quick View into Viewer. With shortcut tooltip.
- [ ] Visual cleanup like removing padding when in Quick View.
- [ ] Spacebar shortcut now opens in Quick View and then Shift to switch to Viewer
- [ ] Shift+Spacebar opens in Viewer

### Attachments
<img width="1920" alt="quick_view_v001" src="https://github.com/ynput/ayon-frontend/assets/49156310/980f9001-fdbb-4d93-a57b-38d4756cf0cf">

**Comment by Innders** [comment]
The viewer is already really fast. Is this actually needed now @mkolar ? It might be complicating things just for the sake of it.

**Comment by mkolar** [comment]
I think we can close this as not needed. The viewer is fast and simple enough
