### ISSUE TITLE
Settings URL: Expand and scroll to setting attribute.

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#640]
## Story

I want easy access to the settings attribute from a settings URI like `ayon+settings://maya/create/CreateAss`

### Problems

> why this URI `ayon+settings://maya/create/CreateAss` is not bringing me to the desired location?

Fixing that would provide easier access to the settings for testing or when someone points you to it via URI.

_Potentially!_ this may also allow it to work to "LINK" to another attribute setting from an attribute's tooltip by using a link? (is that possible?)

### Proposal

I think what's just lacking is:
- Scroll to the section
- Expand the section if it's a collapsible section
- If it's in collapsible sections, expand up to the setting field.

E.g. this `ayon+settings://maya/create/CreateAss/default_variants` does select the attribute, but doesn't scroll to it nor expands to it.

## TODO

- [ ] Scroll to the section
- [ ] Expand the section if it's a collapsible section
- [ ] If it's in collapsible sections, expand up to the setting field.
