### ISSUE TITLE
Reviewables: Easily find all products with reviewables

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#644]
## Story

As a producer I may want to see all products that have relevant reviewables.

### Problems

Currently there may be many products that have no reviewables, which may want to be ignored if just viewing the list of products looking for reviewables.

For example here, find my reviewables:
![image](https://github.com/user-attachments/assets/80678f7d-2d24-4051-9834-f7b8f348347f)

Could be nice also if this dropdown right top in the viewer could also be toggled to list only those with reviewables:

![image](https://github.com/user-attachments/assets/7cfb47a2-e3b1-42e0-9749-3a59a614c037)

### Proposal

Be able to filter to list only products in the browser that currently have reviewables.

## TODO

- [ ] Filter to products with reviewables

**Comment by Innders** [comment]
I totally agree that products should be filterable by reviewables.

The problem right now is that we just keep adding more and more filters to the top bar. 

It's not a sustainable solution and so s rethink needs to be done around the whole filtering system and UI.

This applies in a lot of pages, so a reusable solution would be nice.

**Comment by Innders** [comment]
@BigRoy what if it was as simple as sorting the products by `hasReviewables` and adding the reviewables icon (`play_circle`)

![image](https://github.com/user-attachments/assets/a3d6bf6d-98f4-4c5b-911b-30b5551b8e2b)

**Comment by Innders** [comment]
@flynput 

- [ ] Order products list in viewer by `hasReviewables` and then `alphabetically`.
- [ ] Add a `play_circle` icon for list items with reviewables.
- [ ] Add new a column to the middle browser that shows a `play_circle` icon if the version has a reviewable. The column should also be sortable.

![image](https://github.com/user-attachments/assets/297d0db8-bc7a-4761-8069-12e93774f712)

**Comment by mkolar** [comment]
I wouldn't do any work on this specifically. It will be solved by redesign of browser and filtering in general
