### ISSUE TITLE
Feed: Cannot identify status changes for multiple selected folders/tasks/versions

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#665]
There's folders selected, which status changes belongs to which folder?
**Current**
![image](https://github.com/user-attachments/assets/9767be64-34f4-4415-8f3e-39adb2e7282b)

**Target**
![image](https://github.com/user-attachments/assets/3da6797b-d5c7-4813-b2c1-a864c96335d7)

- [ ] When activity is **not** origin as `(label || name)` in brackets at the end.
- [ ] Versions suffixes add the product name and version `(productName - version)` `(layoutMain - v002)`
- [ ] Activities from all from different entities are getting "merged". Only merge activities of same entity (id).

**Pending Approval**
- [ ] Only ever show "origin" status activities. (Folder doesn't show product/version/tasks statuses).

**Comment by BigRoy** [comment]
>  Only when multiple entities selected.

Just want to remark that this issue isn't only on selecting multiple entities.
When selecting a single folder it looks like activity feed displays all status changes for all the product's versions of that folder. As such, the issue is also present when just selecting a single folder since you don't know what status change relates to what entity.

**Comment by Innders** [comment]
> Just want to remark that this issue isn't only on selecting multiple entities.

Ah good point, thanks. Maybe status changes shouldn't show at all for "related" entities. Only ever show status changes for the selected origin entity, in this case folder "Hero". WDYT?

**Comment by BigRoy** [comment]
> Ah good point, thanks. Maybe status changes shouldn't show at all for "related" entities. Only ever show status changes for the selected origin entity, in this case folder "Hero". WDYT?

I think that'd be a solid start looking at my crazy list of status changes hehehe. But I think this is better answered by @mkolar or @dee-ynput

**Comment by dee-ynput** [comment]
Do these test data realy match reality?
You would at least have many diffetent datetimes for status status changes.
And that would be a nice overview of activity in a folder.
At least I think that was Milan's intend.
In which case, showing the origins even on single selection would be indeed required.

But... The overview of statuses will be solved by Prod Track's Progress View.
So maybe it's not a must have feature anymore in the feeds.

We need our Prod Track Domain Owner @mkolar to sort that out. 😃

**Comment by Innders** [comment]
# Activity suffix combinations

## Versions

Single version selected - no suffix
Multiple versions selected - `[productName - version]` -> `(lookMain - v004)`
![image](https://github.com/user-attachments/assets/95c64254-33df-4f76-ad3b-c52ffe1d5856)

Folder selected (single or multiple) - `[folderName - productName - version]` -> `(pigeon - lookMain - v004)`
![image](https://github.com/user-attachments/assets/4f4b88b0-3be3-4adf-aad3-1509842e3172)

Task selected (single or multiple) - `[taskName - productName - version]` -> `(Lookdev - lookMain - v004)`
![image](https://github.com/user-attachments/assets/3099e834-f1d1-43f2-b677-512598f168fc)

## Folders

Single folder selection - no suffix
Multiple folder selection - `[folderName]` -> `(street)`

## Tasks
Single task selection - no suffix
Multiple task selection - `[taskName]` -> `(Lookdev)`

Sidenote: This bug where the icons don't show up have given me an idea! What if the icons only show for status changes that have no suffix. Then it would be visually obvious when a status change is origin or relation.

![image](https://github.com/user-attachments/assets/9a977749-0dd5-4a70-86c5-00aae609c106)
