### ISSUE TITLE
Attributes: Enum supports colours and icons

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#814]
## TODO

- [x] Value use normal text input
- [x] Color select row
- [x] Icon select row
- [x] Items should be sortable
- [x] Editing open/close (clicking on whole header not just icon)

### Attachments
![image](https://github.com/user-attachments/assets/01e684ae-fc4e-46e6-b23e-e91e536a949b)

### Notes

- We have an `IconSelect` dropdown already.
- We have an `InputColor` picker already but it might be easier to actually use the native one.
- Value should automatically fill based on Label (with special characters removed and spaces replace with -)
