### ISSUE TITLE
Attributes: User friendly types

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#826]
## Story

I am not a developer and do not know what "list of strings" means.

### Problems

- `list of strings` `string`, `enumerator` and `boolean` are all developer terms and hard to understand.
- `list of strings` and `string` + enumerator is even more confusing

### Proposal

Come up with user friendly terms to describe these technical types.
`string` -> **Text**
`string + enumerator` -> **Select**
`list of strings` -> **Multi-select** + Switch to toggle **Custom options**

## TODO

- [ ] Split **string** into two type options -> **text** and **select** (string with enum).
- [ ] Rename **list of strings** to **Multi-select**.
- [ ] **Multi-select** has an option to allow **custom** options.
- [ ] Maybe some icons for the types would be nice?

### Attachments
Inspiration
![image](https://github.com/user-attachments/assets/c9fc3e12-918b-4fc4-bf2b-9da562bd494b)
